- name: "новая-заявка"
  color: "0052CC"
  description: "Новая заявка от студента"

- name: "ожидает-ревью"
  color: "FBCA04"
  description: "Ожидает ревью менторов"

- name: "в-процессе-ревью"
  color: "F9D0C4"
  description: "Менторы проводят ревью"

- name: "требуются-доработки"
  color: "D93F0B"
  description: "Требуются доработки от студента"

- name: "одобрено"
  color: "0E8A16"
  description: "Одобрено для портфолио"

- name: "добавлено-в-портфолио"
  color: "5319E7"
  description: "Проект добавлен в портфолио"

- name: "фидбэк"
  color: "1D76DB"
  description: "Содержит фидбэк менторов"

- name: "срочно"
  color: "B60205"
  description: "Требует срочного внимания"
