# Конфигурация GitHub Project для менторства

name: "Программа менторства"
description: "Трекер заявок и проектов студентов"

columns:
  - name: "📥 Новые заявки"
    preset: "pull_request_with_property"
    
  - name: "🔍 На ревью"
    preset: "pull_requests"
    
  - name: "🔄 Требуют доработок"
    preset: "pull_requests"
    
  - name: "✅ Одобрено"
    preset: "pull_requests"
    
  - name: "🏆 В портфолио"
    preset: "pull_requests"

automation:
  - pulls:
      label: "новая-заявка"
    column: "📥 Новые заявки"
    
  - pulls:
      label: "в-процессе-ревью"
    column: "🔍 На ревью"
    
  - pulls:
      label: "требуются-доработки"
    column: "🔄 Требуют доработок"
    
  - pulls:
      label: "одобрено"
    column: "✅ Одобрено"
    
  - pulls:
      label: "добавлено-в-портфолио"
    column: "🏆 В портфолио"
